create table identity_credential_history (
    id bigint generated by default as identity primary key,
    subject_type varchar(40) not null,
    subject_key varchar(160) not null,
    previous_status varchar(40),
    next_status varchar(40) not null,
    source varchar(40) not null,
    reason varchar(255),
    updated_by varchar(80),
    created_at timestamp(6) not null
);

create index idx_identity_credential_history_subject
    on identity_credential_history (subject_type, subject_key, created_at desc);
