create table chain_business_records (
    id bigint generated by default as identity primary key,
    dataset_id varchar(40) not null,
    event_type varchar(80) not null,
    reference_id varchar(80) not null,
    business_status varchar(40) not null,
    anchor_status varchar(40) not null,
    actor_id varchar(80) not null,
    actor_role varchar(40) not null,
    actor_org varchar(120) not null,
    chain_provider varchar(40),
    chain_group varchar(40),
    contract_name varchar(120),
    contract_address varchar(255),
    event_hash varchar(255),
    chain_tx_hash varchar(255),
    detail varchar(1000),
    anchor_error varchar(1000),
    anchored_at timestamp(6) not null
);

create index idx_chain_business_records_dataset_time
    on chain_business_records (dataset_id, anchored_at desc);
